базовое приложение телебот
golang-tech-leaders/telebot pull request #3
Opened 2020-10-19 15:45 UTC by Trepka

2020-10-20 20:12 UTC, ilyakaznacheev requested changes

2020-10-20 20:12 UTC, ilyakaznacheev commented on cmd/main.go
> +	botToken := "1002130423:AAG1fk3_C4PSn3172SATn29jgtp5T7R5o60"
Вынести в отдельную константу на уровне пакета, в дальнейшем - в конфигурацию через переменные окружения

2020-10-20 20:12 UTC, ilyakaznacheev commented on cmd/main.go
> +	botApi := "https://api.telegram.org/bot"
Вынести в константу на уровне пакета

2020-10-20 20:12 UTC, ilyakaznacheev commented on cmd/main.go
> +			offset = update.UpdateId + 1
UpdateId всегда идут по порядку?

Если нет, работать будет некорректно

2020-10-20 20:12 UTC, ilyakaznacheev commented on cmd/main.go
> +	botMessage.Text = update.Message.Text
Можно написать проще:

```go
botMessage := BotMessage{
	ChatId: update.Message.Chat.ChatId,
	Text: update.Message.Text,
}
```

Ошибки нет, просто так короче и понятнее

2020-10-20 20:12 UTC, ilyakaznacheev commented on cmd/main.go
> +	buf, err := json.Marshal(botMessage)
Здесь вроде как нужно передавать указатель на `botMessage`, работает так?

2020-10-20 20:12 UTC, ilyakaznacheev commented on cmd/main.go
> +	_, err = http.Post(botUrl+"/sendMessage", "application/json", bytes.NewBuffer(buf))
Имеет смысл кроме err (ошибка при отправке) проверить http статус из респонса на предмет 2xx

2020-10-22 15:15 UTC, Trepka commented on cmd/main.go
> +	botToken := "1002130423:AAG1fk3_C4PSn3172SATn29jgtp5T7R5o60"
Вынес, дополнительно сделал чтение из переменной окружения

2020-10-22 15:15 UTC, Trepka commented on cmd/main.go
> +	botApi := "https://api.telegram.org/bot"
Вынес

2020-10-22 15:16 UTC, Trepka commented on cmd/main.go
> +			offset = update.UpdateId + 1
Да, по порядку, но на всякий случай написал сортировку

2020-10-22 15:16 UTC, Trepka commented on cmd/main.go
> +	botMessage.Text = update.Message.Text
Сделал

2020-10-22 15:16 UTC, Trepka commented on cmd/main.go
> +	buf, err := json.Marshal(botMessage)
Работает и без указателя и с указателем

2020-10-22 15:18 UTC, Trepka commented on cmd/main.go
> +	_, err = http.Post(botUrl+"/sendMessage", "application/json", bytes.NewBuffer(buf))
Проверку добавил. Как нормально обрабатывать ошибки - еще поизучаю документацию.

2020-10-26 14:00 UTC, ilyakaznacheev approved these changes

2020-10-26 14:01 UTC, ilyakaznacheev commented
Closes #2

2020-10-26 14:01 UTC, merged